# Generated by Django 3.2.10 on 2024-06-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
