# Generated by Django 3.2.10 on 2024-06-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_blog", "0002_employees_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employees",
            name="age",
        ),
    ]
