# Generated by Django 3.2.10 on 2024-06-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0007_products_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Напишите имя сотрудника'),
        ),
    ]
