# Generated by Django 5.0.6 on 2024-06-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_blog", "0009_auto_20240611_1947"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("author", models.CharField(max_length=120)),
            ],
        ),
    ]
